### ISSUE TITLE
Investigate x3dom import issue

### ISSUE THREAD

**Issue by jamesleesaunders** [jamesleesaunders/d3-x3d#53]
### Summary

Import x3dom not working as expected. Unable to to add x3dom.fields.SFVec3f.

### Detail

The vector field component and chart both require `x3dom.fields.SFVec3f` functions. I have tried adding `import * as x3dom from "x3dom";` at the top of these files so the IDE (WebStorm) does not complain, however on building d3-x3dom I get errors `ReferenceError: navigator is not defined`. 
I am not sure how to import x3dom (or even if I should), as x3dom is not a module.

Navigator is part of the browser window object which does not exist in tests.

### Relevant Files

`/src/component/vectorFields.js`
`/src/chart/vectorFieldChart.js`

**Comment by jamesleesaunders** [comment]
```
MacBook-Pro:d3-x3dom jim$ tape test/indexTest.js 
/Users/jim/Sites/d3-x3dom/node_modules/x3dom/x3dom.js:7
var x3dom={canvases:[],x3dNS:'http://www.web3d.org/specifications/x3d-namespace',x3dextNS:'http://philip.html5.org/x3d/ext',xsltNS:'http://www.w3.org/1999/XSL/x3dom.Transform',xhtmlNS:'http://www.w3.org/1999/xhtml'};x3dom.nodeTypes={};x3dom.nodeTypesLC={};x3dom.components={};x3dom.geoCache=[];x3dom.caps={PLATFORM:navigator.platform,AGENT:navigator.userAgent,RENDERMODE:"HARDWARE"};x3dom.registerNodeType=function(nodeTypeName,componentName,nodeDef){if(x3dom.components[componentName]===undefined){x3dom.components[componentName]={};}
                                                                                                                                                                                                                                                                                                                           ^

ReferenceError: navigator is not defined
    at Object.<anonymous> (/Users/jim/Sites/d3-x3dom/node_modules/x3dom/x3dom.js:7:316)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at version (/Users/jim/Sites/d3-x3dom/build/d3-x3dom.js:10:105)
    at Object.<anonymous> (/Users/jim/Sites/d3-x3dom/build/d3-x3dom.js:13:2)
```
